name: flutter_lab_assignment_3
description: A Flutter assignment project for albums and photos.
publish_to: 'none'
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  flutter_bloc: ^8.1.3
  http: ^0.13.5
  go_router: ^10.0.0

flutter:
  uses-material-design: true




